"""
Canada TSC Aerodromes Constants

List of Canadian aerodromes with facility and reduction information.
Used for Canadian overflight charge calculations.
Converted from JavaScript CANADA_TSC_AERODROMES.js

Requirements: 6.4
"""

CANADA_TSC_AERODROMES = [
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYXX",
        "iata": "YXX",
        "name": "Abbotsford",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CZBB",
        "iata": "YDT",
        "name": "Boundary Bay",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYBR",
        "iata": "YBR",
        "name": "Brandon",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYYC",
        "iata": "YYC",
        "name": "Calgary Int'l",
    },
    {
        "altName": "STANFIELD INTL",
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYHZ",
        "iata": "YHZ",
        "name": "Calgary/Springbank",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYBL",
        "iata": "YBL",
        "name": "Campbell River",
    },
    {
        "altName": "WEST KOOTENAY REGIONAL",
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYCG",
        "iata": "YCG",
        "name": "Castlegar",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CCH4",
        "iata": "YHG",
        "name": "Charlottetown",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYRC",
        "iata": None,
        "name": "Chicoutimi/Saint-Honoré",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYQ",
        "iata": "YYQ",
        "name": "Churchill",
    },
    {
        "altName": "CANADIAN ROCKIES INTL",
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXC",
        "iata": "YXC",
        "name": "Cranbrook",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYVZ",
        "iata": "YVZ",
        "name": "Deer Lake",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": True},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYEG",
        "iata": "YEG",
        "name": "Edmonton Int'l",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CZVL",
        "iata": None,
        "name": "Edmonton/Villeneuve",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYMM",
        "iata": "YMM",
        "name": "Fort McMurray",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYE",
        "iata": "YYE",
        "name": "Fort Nelson",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXJ",
        "iata": "YXJ",
        "name": "Fort St. John",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYFC",
        "iata": "YFC",
        "name": "Fredericton",
    },
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQX",
        "iata": "YQX",
        "name": "Gander (IFSS)",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYND",
        "iata": "YND",
        "name": "Gatineau",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQU",
        "iata": "YQU",
        "name": "Grande Prairie",
    },
    {
        "altName": "STANFIELD INTL",
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYHZ",
        "iata": "YHZ",
        "name": "Halifax",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "YHML",
        "iata": "HLT",
        "name": "Hamilton",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYOJ",
        "iata": "YOJ",
        "name": "High Level",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYGR",
        "iata": "YGR",
        "name": "Îles-de-la-Madeleine",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYEV",
        "iata": "YEV",
        "name": "Inuvik",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYFB",
        "iata": "YFB",
        "name": "Iqaluit",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": True},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYKA",
        "iata": "YKA",
        "name": "Kamloops",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYLW",
        "iata": "YLW",
        "name": "Kelowna",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQK",
        "iata": "YQK",
        "name": "Kenora",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYGK",
        "iata": "YGK",
        "name": "Kingston",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYKF",
        "iata": "YKF",
        "name": "Kitchener/Waterloo",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYVP",
        "iata": "YVP",
        "name": "Kuujjuaq",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYGL",
        "iata": "YGL",
        "name": "La Grande-Rivière",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYVC",
        "iata": "YVC",
        "name": "La Ronge",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYNJ",
        "iata": "YLY",
        "name": "Langley",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQL",
        "iata": "YQL",
        "name": "Lethbridge",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYLL",
        "iata": "YLL",
        "name": "Lloydminster",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": True},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXU",
        "iata": "YXU",
        "name": "London",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXH",
        "iata": "YXH",
        "name": "Medicine Hat",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQM",
        "iata": "YQM",
        "name": "Moncton",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYY",
        "iata": "YYY",
        "name": "Mont-Joli",
    },
    {
        "altName": "PIERRE-ELLIOTT-TRUDEAU INTL",
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYUL",
        "iata": "CYUL",
        "name": "Montréal/Dorval",
    },
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYMX",
        "iata": "YMX",
        "name": "Montréal/Mirabel",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYHU",
        "iata": "YHU",
        "name": "Montréal/Saint-Hubert",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYCD",
        "iata": "YCD",
        "name": "Nanaimo",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYVQ",
        "iata": "YVQ",
        "name": "Norman Wells",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYB",
        "iata": "YYB",
        "name": "North Bay",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYOO",
        "iata": "YOO",
        "name": "Oshawa",
    },
    {
        "altName": "MACDONALD-CARTIER INTL",
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYOW",
        "iata": "YOW",
        "name": "Ottawa",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYPE",
        "iata": "YPE",
        "name": "Peace River ",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYF",
        "iata": "YYF",
        "name": "Penticton",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYPK",
        "iata": None,
        "name": "Pitt Meadows",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYZT",
        "iata": "YZT",
        "name": "Port Hardy",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYPA",
        "iata": "YPA",
        "name": "Prince Albert",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXS",
        "iata": "YXS",
        "name": "Prince George",
    },
    {
        "altName": "JEAN LESAGE INTL",
        "facility": {"tower": True, "fss": False, "fic": True},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYQB",
        "iata": "YQB",
        "name": "Québec",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYRT",
        "iata": "YRT",
        "name": "Rankin Inlet",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYQF",
        "iata": "YQF",
        "name": "Red Deer",
    },
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYQR",
        "iata": "YQR",
        "name": "Regina",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYUY",
        "iata": "YUY",
        "name": "Rouyn",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYSJ",
        "iata": "YSJ",
        "name": "Saint John",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYJN",
        "iata": "YJN",
        "name": "Saint-Jean",
    },
    {
        "altName": "JOHN G. DIEFENBAKER INTL",
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYXE",
        "iata": "YXE",
        "name": "Saskatoon",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYAM",
        "iata": "YAM",
        "name": "Sault Ste. Marie",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYZV",
        "iata": "YZV",
        "name": "Sept-Îles",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXL",
        "iata": "YXL",
        "name": "Sioux Lookout",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYD",
        "iata": "YYD",
        "name": "Smithers",
    },
    {
        "altName": "NIAGARA DISTRICT",
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYSN",
        "iata": "YCM",
        "name": "St. Catharines",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYYT",
        "iata": "YYT",
        "name": "St. John's",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYSB",
        "iata": "YSB",
        "name": "Sudbury",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXT",
        "iata": "YXT",
        "name": "Terrace",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYTH",
        "iata": "YTH",
        "name": "Thompson",
    },
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYQT",
        "iata": "YQT",
        "name": "Thunder Bay",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYTS",
        "iata": "YTS",
        "name": "Timmins",
    },
    {
        "altName": "BILLY BISHOP TORONTO CITY AIRPORT",
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYTZ",
        "iata": "YTZ",
        "name": "Toronto Island City Centre",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYYZ",
        "iata": "YYZ",
        "name": "Toronto LBPIA",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYVO",
        "iata": "YVO",
        "name": "Val-d'Or",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYHC",
        "iata": "CXH",
        "name": "Vancouver Harbour",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYVR",
        "iata": "YVR",
        "name": "Vancouver Int'l",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYYJ",
        "iata": "YYJ",
        "name": "Victoria",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYWH",
        "iata": "YWH",
        "name": "Victoria Harbour",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYWK",
        "iata": "YWK",
        "name": "Wabush",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYZU",
        "iata": "YZU",
        "name": "Whitecourt",
    },
    {
        "altName": "ERIK NIELSEN INTL",
        "facility": {"tower": True, "fss": False, "fic": True},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYXY",
        "iata": "YXY",
        "name": "Whitehorse",
    },
    {
        "facility": {"tower": False, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYWL",
        "iata": "YWL",
        "name": "Williams Lake",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYQG",
        "iata": "YQG",
        "name": "Windsor",
    },
    {
        "altName": "JAMES ARMSTRONG RICHARDSON INTL",
        "facility": {"tower": True, "fss": False, "fic": True},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYWG",
        "iata": "YWG",
        "name": "Winnipeg",
    },
    {
        "facility": {"tower": True, "fss": False, "fic": False},
        "reduction": {"sixtyFiveKm": True, "thirtyFiveKm": False},
        "icao": "CYAV",
        "iata": None,
        "name": "Winnipeg/St. Andrews",
    },
    {
        "facility": {"tower": True, "fss": True, "fic": False},
        "reduction": {"sixtyFiveKm": False, "thirtyFiveKm": True},
        "icao": "CYZF",
        "iata": "YZF",
        "name": "Yellowknife",
    },
]
