"""
Country Name Constants

Country name mappings used in formula calculations.
Spelling/case based on world_firs_optimized.json
Converted from JavaScript COUNTRY_NAME_CONSTANTS.js

Requirements: 6.2
"""

COUNTRY_NAME_CONSTANTS = {
    "AFGHANISTAN": "Afghanistan",
    "ALGERIA": "Algeria",
    "ANGOLA": "Angola",
    "ARGENTINA": "Argentina",
    "ARUBA": "Aruba",
    "AUSTRALIA": "Australia",
    "ASHGABAT": "Ashgabat",
    "AZERBAIJAN": "Azerbaijan",
    "BAHAMAS": "Bahamas",
    "BAHRAIN": "Bahrain",
    "BANGLADESH": "Bangladesh",
    "BELIZE": "Belize",
    "BERMUDA": "Bermuda",
    "BOTSWANA": "Botswana",
    "BRAZIL": "Brazil",
    "CANADA": "Canada",
    "CAPE_VERDE": "Cape Verde",
    "CHAD": "Chad",
    "CHILE": "Chile",
    "CHINA": "China",
    "COLOMBIA": "Colombia",
    "CONGO_DRC": "Congo DRC",
    "COSTARICA": "Costa Rica",
    "CUBA": "Cuba",
    "DOMINICAN_REPUBLIC": "Dominican Republic",
    "ECUADOR": "Ecuador",
    "EGYPT": "Egypt",
    "ELSALVADOR": "El Salvador",
    "ETHIOPIA": "Ethiopia",
    "FIJI": "Fiji",
    "FRENCH_GUIANA": "French Guiana (France)",
    "FRENCH_POLYNESIA": "French Polynesia",
    "GHANA": "Ghana",
    "GREENLAND": "Greenland",
    "GUYANA": "Guyana",
    "HAITI": "Haiti",
    "HONDURAS": "Honduras",
    "HONGKONG": "Hong Kong",
    "ICELAND": "Iceland",
    "INDIA": "India",
    "INDONESIA": "Indonesia",
    "IRAN": "Iran",
    "IRAQ": "Iraq",
    "ISRAEL": "Israel",
    "JAMAICA": "Jamaica",
    "JAPAN": "Japan",
    "JORDAN": "Jordan",
    "KAZAKHSTAN": "Kazakhstan",
    "KUWAIT": "Kuwait",
    "KYRGYZSTAN": "Kyrgyzstan",
    "LAOS": "Laos",
    "LIBERIA": "Liberia",
    "LIBYA": "Libya",
    "MADAGASCAR": "Madagascar",
    "MAGADAN_SOKOL_EAST": "MAGADAN SOKOL EAST",
    "MALAWI": "Malawi",
    "MALAYSIA": "Malaysia",
    "MALDIVES": "Maldives",
    "MAURITIUS": "Mauritius",
    "MEXICO": "Mexico",
    "MONGOLIA": "Mongolia",
    "MOROCCO": "Morocco",
    "MOZAMBIQUE": "Mozambique",
    "MYANMAR": "Myanmar",
    "NAMIBIA": "Namibia",
    "NAURU": "Nauru",
    "NEPAL": "Nepal",
    "NETHERLANDS_ANTILLES": "Netherlands Antilles",
    "NEW_ZEALAND": "New Zealand",
    "NIGER": "Niger",
    "NORTH_KOREA": "North Korea",
    "OMAN": "Oman",
    "PAKISTAN": "Pakistan",
    "PANAMA": "Panama",
    "PAPUA_NEW_GUINEA": "Papua New Guinea",
    "PERU": "Peru",
    "PHILIPPINES": "Philippines",
    "PORTUGAL": "Portugal",
    "RUSSIAN_FEDERATION": "Russian Federation",
    "RUSSIA": "Russia",
    "IRKUTSK": "Irkutsk",
    "SAUDI_ARABIA": "Saudi Arabia",
    "SENEGAL": "Senegal",
    "SEYCHELLES": "Seychelles",
    "SINGAPORE": "Singapore",
    "SOLOMON_ISLANDS": "Solomon Islands",
    "SOMALIA": "Somalia",
    "SOUTH_AFRICA": "South Africa",
    "SOUTH_KOREA": "South Korea",
    "SPAIN": "Spain",
    "SRI_LANKA": "Sri Lanka",
    "SUDAN": "Sudan",
    "SURINAME": "Suriname",
    "SYRIA": "Syria",
    "TAIWAN": "Taiwan",
    "TAJIKISTAN": "Tajikistan",
    "THAILAND": "Thailand",
    "TRINIDAD_AND_TOBAGO": "Trinidad and Tobago",
    "TUNISIA": "Tunisia",
    "TURKMENISTAN": "Turkmenistan",
    "TURKS_AND_CAICOS": "Turks and Caicos",
    "UK": "UK",
    "UNITED_ARAB_EMIRATES": "United Arab Emirates",
    "USA": "USA",
    "UZBEKISTAN": "Uzbekistan",
    "VENEZUELA": "Venezuela",
    "VIETNAM": "Vietnam",
    "ZAMBIA": "Zambia",
}
