"""
FIR Names Per Country Constants

Mapping of countries to their Flight Information Region (FIR) identifiers.
Created from a REDUCE of world_firs_optimized.json
Converted from JavaScript FIR_NAMES_PER_COUNTRY_CONSTANTS.js

Requirements: 6.3
"""

FIR_NAMES_PER_COUNTRY = {
    "GHANA": ["DGAC"],
    "ETHIOPIA": ["HAAA"],
    "KAZAKHSTAN": ["UATT", "UAAX", "UACX", "UAII"],
    "USA": [
        "KZAB",
        "PAZA",
        "PAZA",
        "PAZA",
        "PAZN",
        "PAZN",
        "KZTL",
        "KZBW",
        "KZAU",
        "KZOB",
        "KZDV",
        "KZFW",
        "KZHU",
        "KZHU",
        "KZID",
        "KZJX",
        "KZKC",
        "KZLA",
        "KZME",
        "KZMA",
        "KZMA",
        "KZMP",
        "KZNY",
        "KZWY",
        "KZWY",
        "KZOA",
        "KZAK",
        "KZAK",
        "KZLC",
        "TJZS",
        "KZSE",
        "KZDC",
    ],
    "ALGERIA": ["DAAA"],
    "BRAZIL": ["SBAZ", "SBAO", "SBBS", "SBCW", "SBRE"],
    "JORDAN": ["OJAC"],
    "NETHERLANDS": ["EHAA"],
    "TURKEY": ["LTAA", "LTBB"],
    "MADAGASCAR": ["FMMM"],
    "CHILE": ["SCFZ", "SCIZ", "SCTZ", "SCCZ", "SCEZ"],
    "RUSSIAN FEDERATION": [
        "ULAA",
        "UELL",
        "UMKK",
        "UHHH",
        "UNKL",
        "UERR",
        "ULMM",
        "ULMM",
        "ULMM",
        "ULMM",
        "UNNT",
        "UHPP",
        "UHPP",
        "UWWW",
        "USTV",
        "ULWW",
        "UEEE",
        "USSS",
    ],
    "ASHGABAT": ["UTAA"],
    "EGYPT": ["HHAA", "HECC"],
    "PARAGUAY": ["SGFA"],
    "GREECE": ["LGGG"],
    "NEW ZEALAND": ["NZZO", "NZZO", "NZZC"],
    "IRAQ": ["ORBB"],
    "BAHRAIN": ["OBBB"],
    "AZERBAIJAN": ["UBBA"],
    "THAILAND": ["VTBB"],
    "SPAIN": ["LECB", "GCCC", "LECM"],
    "COLOMBIA": ["SKEC", "SKED"],
    "CHINA": [
        "ZBPE",
        "ZGZU",
        "VHHK",
        "ZPKM",
        "ZLHW",
        "ZJSA",
        "ZSHA",
        "ZYSH",
        "ZWUQ",
        "ZHWH",
    ],
    "MOZAMBIQUE": ["FQBE"],
    "LEBANON": ["OLBB"],
    "SERBIA": ["LYBA"],
    "KYRGYZSTAN": ["UAFX"],
    "NORWAY": ["ENOB", "ENOR"],
    "FRANCE": ["LFBB", "LFRR", "LFMM", "LFFF", "LFEE"],
    "SLOVAKIA": ["LZBB"],
    "CONGO BRAZZAVILLE": ["FCCC"],
    "GERMANY": ["EDWW", "EDGG", "EDMM"],
    "ITALY": ["LIBB", "LIMM", "LIRR"],
    "AUSTRALIA": ["YBBB", "YMMM"],
    "BELGIUM": ["EBBU"],
    "ROMANIA": ["LRBB"],
    "HUNGARY": ["LHCC"],
    "SOUTH AFRICA": ["FACA", "FAJX", "FAJO"],
    "MOROCCO": ["GMMM"],
    "FRENCH GUIANA (FRANCE)": ["SOOO"],
    "HONDURAS": ["MHTG"],
    "EUR": ["USCC"],
    "INDIA": ["VOMF", "VIDF", "VECF", "VABF"],
    "MOLDOVA": ["LUUU"],
    "SRI LANKA": ["VCCC"],
    "ARGENTINA": ["SAVF", "SACF", "SAEF", "SAMF", "SARR"],
    "NETHERLANDS ANTILLES": ["TNCF"],
    "SENEGAL": ["GOOO", "GOOO"],
    "SYRIA": ["OSTT"],
    "TANZANIA": ["HTDC"],
    "TURKMENISTAN": ["UTAT", "UTAV", "UTAK"],
    "BANGLADESH": ["VGFR"],
    "UKRAINE": ["UKDV", "UKBV", "UKLV", "UKOV", "UKFV"],
    "TAJIKISTAN": ["UTDD"],
    "CANADA": ["CZEG", "CZQX", "CZQX", "CZQM", "CZUL", "CZYZ", "CZVR", "CZWG"],
    "UNITED ARAB EMIRATES": ["OMAE"],
    "UGANDA": ["HUEC"],
    "FINLAND": ["EFIN"],
    "JAPAN": ["RJJJ"],
    "BOTSWANA": ["FBGR"],
    "GUYANA": ["SYGC"],
    "SWITZERLAND": ["LSAS"],
    "ECUADOR": ["SEFG"],
    "CUBA": ["MUFH"],
    "VIETNAM": ["VVVV", "VVTS"],
    "ZIMBABWE": ["FVHF"],
    "SOLOMON ISLANDS": ["AGGG"],
    "SOUTH KOREA": ["RKRR"],
    "IRKUTSK": ["UIII"],
    "INDONESIA": ["WIIF", "WAAZ"],
    "SAUDI ARABIA": ["OEJD"],
    "AFGHANISTAN": ["OAKX"],
    "NIGERIA": ["DNKK"],
    "PAKISTAN": ["OPKR", "OPLR"],
    "NEPAL": ["VNSM"],
    "RUSSIA": ["UMKD", "UUWV", "UHSH", "URRV", "ULLL", "UUYY", "UGEE"],
    "SUDAN": ["HSSX"],
    "JAMAICA": ["MKJK"],
    "CONGO DRC": ["FZZA"],
    "KIROV": ["USKK"],
    "DENMARK": ["EKDK"],
    "BRUNEI / MALAYSIA": ["WBFC"],
    "KOTLAS": ["ULKK"],
    "MALAYSIA": ["WMFC"],
    "KUWAIT": ["OKAC"],
    "BOLIVIA": ["SLLF"],
    "MALAWI": ["FWLL"],
    "PERU": ["SPIM"],
    "PORTUGAL": ["LPPC", "LPPO"],
    "SLOVENIA": ["LJLA"],
    "UK": ["EGTT", "EGPX", "EGGX"],
    "ANGOLA": ["FNAN"],
    "ZAMBIA": ["FLFI"],
    "MAGADAN OCEANIC EAST": ["UHMM"],
    "MAGADAN OCEANIC WEST": ["UHMM"],
    "MAGADAN SOKOL EAST": ["UHMM"],
    "MAGADAN WEST": ["UHPP"],
    "MAGNITOGORSK": ["USCM"],
    "VENEZUELA": ["SVZM"],
    "MALDIVES": ["VRMF"],
    "MALTA": ["LMMM"],
    "PHILIPPINES": ["RPHI"],
    "MAURITIUS": ["FIMM"],
    "MEXICO": ["MMFO", "MMFR"],
    "BELARUS": ["UMMV"],
    "SOMALIA": ["HCSM"],
    "URUGUAY": ["SUEO"],
    "OMAN": ["OOMM"],
    "CHAD": ["FTTT"],
    "FIJI": ["NFFF", "NFFF"],
    "KENYA": ["HKNA"],
    "NARYAN-MAR": ["ULAM"],
    "BAHAMAS": ["MYNA"],
    "NAURU": ["ANAU"],
    "NIGER": ["DRRR"],
    "CYPRUS": ["LCCC"],
    "UZBEKISTAN": ["UTNR", "UTSD", "UTTR"],
    "PANAMA": ["MPZL"],
    "SURINAME": ["SMPM"],
    "PERM": ["USPP"],
    "CAMBODIA": ["VDPP"],
    "TRINIDAD AND TOBAGO": ["TTZP"],
    "HAITI": ["MTEG"],
    "PAPUA NEW GUINEA": ["AYPM"],
    "CZECH REPUBLIC": ["LKAA"],
    "NORTH KOREA": ["ZKKP"],
    "ICELAND": ["BIRD"],
    "LATVIA": ["EVRR"],
    "LIBERIA": ["GLRX"],
    "CAPE VERDE": ["GVSC"],
    "YEMEN": ["OYSC"],
    "DOMINICAN REPUBLIC": ["MDCS"],
    "BOSNIA AND HERZEGOVINA": ["LQSB"],
    "SEYCHELLES": ["FSSS"],
    "IRELAND": ["EISN"],
    "SINGAPORE": ["WSJC"],
    "NORTH MACEDONIA": ["LWSS"],
    "BULGARIA": ["LBSR"],
    "GREENLAND": ["BGGL"],
    "SWEDEN": ["ESAA"],
    "FRENCH POLYNESIA": ["NTTT"],
    "TAIWAN": ["RCAA"],
    "ESTONIA": ["EETT"],
    "GEORGIA": ["UGGG"],
    "IRAN": ["OIIX"],
    "ISRAEL": ["LLLL"],
    "ALBANIA": ["LAAA"],
    "LIBYA": ["HLLL"],
    "TUNISIA": ["DTTC"],
    "MONGOLIA": ["ZMUB"],
    "LAOS": ["VLIV"],
    "LITHUANIA": ["EYVL"],
    "POLAND": ["EPWW"],
    "AUSTRIA": ["LOVV"],
    "NAMIBIA": ["FYWF"],
    "MYANMAR": ["VYYF"],
    "CROATIA": ["LDZO"],
    "RWANDA": ["HRYR"],
    "BURUNDI": ["HBBA"],
}
